server: # REST and WS server
    port: 2333
    address: 0.0.0.0
    http2:
        enabled: false
plugins:
    youtube:
        enabled: true
        allowSearch: true
        allowDirectVideoIds: true
        allowDirectPlaylistIds: true
        clients:
            - MUSIC
            # - ANDROID_TESTSUITE
            # - WEB
            # - TVHTML5EMBEDDED
lavalink:
    plugins:
        - dependency: "dev.lavalink.youtube:youtube-plugin:1.8.3"
          snapshot: false
    server:
        password: "youshallnotpass"
        sources:
            youtube: false
            bandcamp: true
            soundcloud: true
            twitch: true
            vimeo: true
            nico: true
            http: false
            local: true
        filters: # All filters are enabled by default
            volume: true
            equalizer: true
            karaoke: true
            timescale: true
            tremolo: true
            vibrato: true
            distortion: true
            rotation: true
            channelMix: true
            lowPass: true
        nonAllocatingFrameBuffer: true
        bufferDurationMs: 1000
        frameBufferDurationMs: 5000
        opusEncodingQuality: 10
        resamplingQuality: LOW
        trackStuckThresholdMs: 5000
        useSeekGhosting: true
        youtubePlaylistLoadLimit: 6
        playerUpdateInterval: 5
        youtubeSearchEnabled: true
        soundcloudSearchEnabled: true
        gc-warnings: true
        #ratelimit:
        #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
        #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
        #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
        #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
        #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
        #youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
        #email: "" # Email of Google account
        #password: "" # Password of Google account
        #httpConfig: # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
        #proxyHost: "localhost" # Hostname of the proxy, (ip or domain)
        #proxyPort: 3128 # Proxy port, 3128 is the default for squidProxy
        #proxyUser: "" # Optional user for basic authentication fields, leave blank if you don't use basic auth
        #proxyPassword: "" # Password for basic authentication

metrics:
    prometheus:
        enabled: false
        endpoint: /metrics

sentry:
    dsn: ""
    environment: ""

logging:
    # upto you if you want to save the logs in a file
    # file:
    #    path: ./logs/

    level:
        root: INFO
        lavalink: INFO

    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includeQueryString: true
        includePayload: true
        maxPayloadLength: 10000

    logback:
        rollingpolicy:
            max-file-size: 1GB
            max-history: 30
